#!/bin/bash

rm -rf build
rm -rf dist
rm -rf lib

rm -rf    ./src/main/javascript
mkdir -p  ./src/main/javascript
cd        ./src/main/proto
clear
./protoc --js_out=import_style=commonjs,binary:../javascript *.proto
cd ../../../

echo "---------- ProtoBuf Finished---------"
echo ""

sh gradlew clean build copyJars release

mkdir lib
cp ./build/libs/*-fat.jar ./lib

echo "---------- Build Finished---------"
echo ""

echo "---------- 构建容器 Start---------"

# 构建Docker部署目录
rm -r deploy
mkdir deploy
cp -r lib deploy
cp -r etc deploy
cp -r bin deploy
mkdir deploy/log

# 构建容器
docker build -t dodofun/vertx:latest . -f Dockerfile

echo "---------- 构建容器 Finished---------"

# echo "---------- Push容器 Start---------"
# 上传到 DOCKER
# docker push dodofun/vertx:latest
# echo "---------- Push容器 Finished---------"

# 上传到阿里云容器
echo "---------- Push容器到阿里云容器 Start---------"
sh aliyun-docker.sh
echo "---------- Push容器到阿里云容器 Finished---------"

# 运行容器
# docker run -d -p 8000:8000 -p 8001:8001 dodofun/vertx:latest
# echo "---------- 服务已启动 ---------"

# 启动并进入容器
# docker run -t -i dodofun/vertx:latest /bin/bash

# 关闭所有容器
# docker stop $(docker ps -a | awk '{ print $1}' | tail -n +2)

# 删除所有容器
# docker rm $(docker ps -a | awk '{ print $1}' | tail -n +2)

# 删除所有镜像
# docker rmi -f $(docker images | awk '{print $3}' |tail -n +2)

# 构建JDK环境容器
# docker build -t dodofun/jdk:latest -f DockerfileEnv .