title = "Configuration"

[project]
    id = 1001
    name = "vertx-starter"

[vertx]
    pool_size = 1024
    max_execute_time = 120000

[runtime]
    service_mode = "dev"
    payload_format = "protobuf"
    print_debug_info = true

[owner]
    name = "lh"

[server]
    type = "http"
    port = 8080

[baseClient]
    type = "http"
    host = "dodo.fun"
    port = 80

[redis]
    type = "single"
    host = "http://127.0.0.1"
    host_lettuce = "39.105.90.92"
    port = 6379
    database = 2
    password = "DODO.fun2018"
    use_kryo_codec = true
    use_protobuf_codec = false
    expire = 3600

[mysql]
    host = "39.105.90.92"
    port = 3306
    username = "root"
    password = "DODO.fun2018"
    database = "dodo"
    driver_name = "com.mysql.jdbc.Driver"
    timeout = 30000
    idleTimeout = 600000
    maxLifetime = 700000
    minimumIdle = 10
    maximumPoolSize = 10

[MNS]
    endpoint = "https://1765638057648149.mns.cn-beijing.aliyuncs.com/"
    access_key = "ppRgMnfETYaohnZB"
    access_secret = "5cZqzxkjkIh1aLf6M2FYCmr2cSrMH9"
    api_log_queue = "api-log"

[aliyunLog]
    project_name = "dodo-demo"
    endpoint = "http://{project_name}.cn-beijing.log.aliyuncs.com"
    access_key = "LTAICWWsWX6u2qJ9"
    access_secret = "1YsL1rKknuAwoRDSskG1VwBELgFuLc"

[cors]
    host = "*"
